import { ClerkProvider } from '@clerk/nextjs'
import { Inter } from 'next/font/google'
import LeftSideBar from '@/components/LeftSideBar'
import MainContainer from '@/components/MainContainer'
import RightSideBar from '@/components/RightSideBar'
import TopBar from '@/components/TopBar'
import BottomBar from '@components/BottomBar'

import '../globals.css'

export const metadata = {
  title: 'Root',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="flex flex-row">
          <LeftSideBar />
          <MainContainer>
            {children}
          </MainContainer>
          <RightSideBar />
        </main>
        <BottomBar />
      </body>
    </html>
  </ClerkProvider>
  )
}
